delete from item;
delete from product;
delete from invoice;
delete from customer;
delete from user_role;
delete from company;
insert into company (id, companyName, city, state, zip, phoneNumber, address) values ('1', 'Hauser Tree Care', 'Madison', 'Wisconsin', '53704', '608-598-9342', '741 ruskin st');
insert into user (id, firstName, lastName, userName, password, companyId) values (1, 'Anthony', 'Poleski', 'anthonyp', 'giggity', 1);
insert into user (id, firstName, lastName, userName, password, companyId) values (2, 'Thomas', 'Thomas', 'thomast', 'thomastp', 1);
insert into customer (id, firstName, lastName, street, postalCode, city, countryId, state, companyId) values ('1', 'Tim', 'Weisman', '5222 Milwaukee Street', '53704', 'Madison', 'BE', 'Wisconsin', '1');
insert into product (id, name, price, vat) values ('1', 'Remove oak tree', '1500', '20');
insert into invoice (id, customerId, invoiceDate, terms, total) values ('1', '1', '2020-2-26', 'Due upon receipt', '1500');
insert into user_role (id, userName, role_name, userId) values ('1', 'anthonyp', 'admin', '1');
insert into user_role (id, userName, role_name, userId) values ('2', 'thomast', 'basic', '2');
insert into item (id, item, productId, invoiceId, quantity, cost) values ('1', '1', '1', '1', '2', '1500');
